### ISSUE TITLE
Please create version tag in Git

### ISSUE THREAD

**Issue by Hades32** [streadway/amqp#312] opened 2018-01-19 08:00 UTC
I'm pinning the version of my Go dependencies (with Glide) and this repo is the last one that I have to reference by commit hash...

Please create Git tags of the form "v1.2" so they can be easier referenced.

Bonus points if you then keep the SemVer standard :)

**Comment by mbresson** [comment] 2018-02-09 03:39
I second that, I'm using _dep_ and it would be great to be able to pin to a specific version tag instead of a commit.
By the way, thanks for this awesome repo! :)

**Comment by sagikazarmark** [comment] 2018-03-05 05:44
Just for reference: #125 

But yeah, semantic versioning and proper package management finally comes to the Go world (and that thing is totally independent from vendoring, so you can still choose to vendor your dependencies AND depend on tagged versions along the way, instead of commit hashes: it makes dependency management much easier)

**Comment by michaelklishin** [comment] 2018-03-07 22:29
Duplicate of #125. I hope one day we will use a proper branching/versioning scheme :/

**Closed by michaelklishin** 2018-03-07 22:29 UTC
