### ISSUE TITLE
Tag or Release

### ISSUE THREAD

**Issue by obierlaire** [streadway/amqp#280] opened 2017-07-18 08:40 UTC
When using dependency management tools such as Glide (https://glide.sh), I think it could be convenient to have some tag or release. When you get this amqp lib as dependency in a go project, with a tag, you will not have any bad surprise (code not working anymore, breaking changes, etc).

Thanks and great work with this library!

**Comment by michaelklishin** [comment] 2017-07-21 13:31
Duplicate of #125.

**Closed by michaelklishin** 2017-07-21 13:31 UTC
