### ISSUE TITLE
Open channel waits forever

### ISSUE THREAD

**Issue by joliver** [streadway/amqp#180] opened 2015-12-30 20:59 UTC
If the network connection to RabbitMQ is unstable (which can be the case over the Internet), we have found multiple times that our code gets stuck in the following location (see stack trace). We are using the default dialer which has a 30-second timeout along with the default 30-second read timeout. I'm investigating how to fix it, but I'm listing this here to document the problem.

Here's the stack trace:

```
goroutine 10 [select, 488 minutes]:
github.com/streadway/amqp.(*Channel).call(0xc21cd2eb00, 0x7f271dc471c0, 0xc24a168610, 0xc21a247c48, 0x1, 0x1, 0x0, 0x0)
    /users/buildserver/src/github.com/streadway/amqp/channel.go:149 +0x5f1
github.com/streadway/amqp.(*Channel).open(0xc21cd2eb00, 0x0, 0x0)
    /users/buildserver/src/github.com/streadway/amqp/channel.go:138 +0x170
github.com/streadway/amqp.(*Connection).openChannel(0xc21aafbe60, 0x0, 0x0, 0x0)
    /users/buildserver/src/github.com/streadway/amqp/connection.go:570 +0x7f
github.com/streadway/amqp.(*Connection).Channel(0xc21aafbe60, 0x1, 0x0, 0x0)
    /users/buildserver/src/github.com/streadway/amqp/connection.go:591 +0x3a
```

Here's the function in the `channel.go` file where the problem is manifest. It appears that the errors channel is never populated thus the select statement blocks forever.

```
func (me *Channel) call(req message, res ...message) error {
    if err := me.send(me, req); err != nil {
        return err
    }

    if req.wait() {
        select { // <-- WAITS RIGHT HERE FOREVER
        case e := <-me.errors:
            ...
        case msg := <-me.rpc:
            ...
        }
    }

    return nil
}
```

**Comment by domashevskiy** [comment] 2016-01-04 08:34
I think this might be the same as in [issue 173](https://github.com/streadway/amqp/issues/173).
There is a possible [fix](https://github.com/WaimaiChaoren/amqp/commit/88561e180aeee809b7cb48a164a71ebc2148c6fd) in a [fork](https://github.com/WaimaiChaoren/amqp) you can try.

**Comment by karlseguin** [comment] 2016-01-11 02:37
Just another update:

closing the rpc channel didn't seem to fix all the problems. Also, it's resulted in some code now trying to write to the closed channels. However, we've done other "fixes" to try to solve various other concurrency issues, so maybe it's related to one of those.

I can say that adding a timeout to that code *does* appear to have solve the issue. Something like:

```
select  {
case <-time.After(time.Second * 10):
  if me.connection.closed {
    return ErrClosed
  }
  me.Close()
  return ErrClosed
case e := <-me.errors:
    ...
case msg := <-me.rpc:
    ...
}
```

Note that this method isn't used when consuming from a queue...so it won't cause a timeout if you're just blocking while reading messages. 

Of course, given that we still don't have it working properly, you should take all of this with a grain of sand.

**Comment by michaelklishin** [comment] 2017-01-05 10:26
Let's consider it a duplicate of #173 and #188.

**Closed by michaelklishin** 2017-01-05 10:26 UTC

**Comment by ghost** [comment] 2024-02-23 13:00
> Let's consider it a duplicate of https://github.com/streadway/amqp/issues/173 and https://github.com/streadway/amqp/pull/188.

From #173:

> Addressed in https://github.com/streadway/amqp/pull/188 and https://github.com/streadway/amqp/pull/223.

From #188:

> Merged in https://github.com/streadway/amqp/pull/223. Thank you!

---

#223 is already in v1.0.0 and v1.1.0, yet, we still have a very similar issue (= hanging at the exact location described here) in github.com/streadway/amqp v1.1.0.

For us, it happens when calling `Close` on the channel (which hangs forever).

**Comment by michaelklishin** [comment] 2024-02-23 23:50
This library (this particular fork if you will) has been out of development for a good couple of years now.

Consider moving to https://github.com/rabbitmq/amqp091-go, or you are entirely on your own own with analyzing what may be going on.
