### ISSUE TITLE
Channel.Publish blocks indefinitely

### ISSUE THREAD

**Issue by bojan-embroker** [streadway/amqp#254] opened 2017-03-21 18:36 UTC
Channel.Publish sometimes blocks indefinitely. The following code is a test case to reproduce this. It reproduces most of time I run it. Adding a sleep between inside the for loop does not help.

```
package main

import (
	"log"

	"github.com/streadway/amqp"
)

func main() {

	const queueName = "q1"

	if conn, stdErr := amqp.Dial("amqp://guest:guest@localhost:5672/"); stdErr != nil {
		log.Fatalln(stdErr)
	} else if channel, stdErr := conn.Channel(); stdErr != nil {
		log.Fatalln(stdErr)
	} else if stdErr := channel.Confirm(false); stdErr != nil {
		log.Fatalln(stdErr)
	} else if _, stdErr := channel.QueueDeclare(
		queueName, //queue
		true,      //durable
		false,     //autodelete
		false,     //exclusive
		false,     //nowait
		nil,       //arguments
	); stdErr != nil {
		log.Fatalln(stdErr)
	} else {
		confirmationChan := channel.NotifyPublish(make(chan amqp.Confirmation))

		for i := 0; i < 10000; i++ {
			log.Println("publish ", i)

			if stdErr := channel.Publish(
				"",        // exchange
				queueName, // routing key
				false,     // mandatory
				false,     // immediate
				amqp.Publishing{
					Body: []byte{},
				}); stdErr != nil {
				log.Fatalln(stdErr)
			} else {
				log.Println("pre confirmation check")
				confirmation := <-confirmationChan
				log.Println("post confirmation check")
				if !confirmation.Ack {
					log.Fatalln("confirmation not ack")
				}
			}
			// time.Sleep(time.Millisecond * 1000)
		}
	}
}
```

**Comment by michaelklishin** [comment] 2017-03-21 18:52
What is in server logs?

**Comment by michaelklishin** [comment] 2017-03-21 18:54
This code assumes you will get one confirmation per message. That's not always the case: RabbitMQ can confirm multiple messages at a time.

Please take a [traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) and see what's going up and down the wire.

**Comment by bojan-embroker** [comment] 2017-03-21 19:23
Thanks for the quick response.

Does that mean RabbitMQ sometimes queues up confirmations i.e. waits to accumulate a few before sending them?

**Comment by bojan-embroker** [comment] 2017-03-21 20:47
Here is the traffic capture of the last several publishes before it blocks:
```
No.     Time           Source                Destination           Protocol Length Info
   1128 0.091681900    127.0.0.1             127.0.0.1             AMQP     85     Basic.Publish x= rk=q1 
   1129 0.091748377    127.0.0.1             127.0.0.1             AMQP     88     Content-Header 
   1130 0.091775358    127.0.0.1             127.0.0.1             TCP      66     5672 → 38245 [ACK] Seq=6390 Ack=11655 Win=44800 Len=0 TSval=80646069 TSecr=80646069
   1131 0.091886102    127.0.0.1             127.0.0.1             AMQP     87     Basic.Ack 
   1132 0.091951429    127.0.0.1             127.0.0.1             AMQP     85     Basic.Publish x= rk=q1 
   1133 0.092015901    127.0.0.1             127.0.0.1             AMQP     88     Content-Header 
   1134 0.092040919    127.0.0.1             127.0.0.1             TCP      66     5672 → 38245 [ACK] Seq=6411 Ack=11696 Win=44800 Len=0 TSval=80646069 TSecr=80646069
   1135 0.092157978    127.0.0.1             127.0.0.1             AMQP     87     Basic.Ack 
   1136 0.092246548    127.0.0.1             127.0.0.1             AMQP     85     Basic.Publish x= rk=q1 
   1137 0.092314854    127.0.0.1             127.0.0.1             AMQP     88     Content-Header 
   1138 0.092340203    127.0.0.1             127.0.0.1             TCP      66     5672 → 38245 [ACK] Seq=6432 Ack=11737 Win=44800 Len=0 TSval=80646069 TSecr=80646069
   1139 0.092451724    127.0.0.1             127.0.0.1             AMQP     87     Basic.Ack 
   1140 0.092515677    127.0.0.1             127.0.0.1             AMQP     85     Basic.Publish x= rk=q1 
   1141 0.092595650    127.0.0.1             127.0.0.1             AMQP     88     Content-Header 
   1142 0.092626995    127.0.0.1             127.0.0.1             TCP      66     5672 → 38245 [ACK] Seq=6453 Ack=11778 Win=44800 Len=0 TSval=80646070 TSecr=80646069
   1143 0.092735005    127.0.0.1             127.0.0.1             AMQP     87     Basic.Ack 
   1144 0.092823870    127.0.0.1             127.0.0.1             AMQP     85     Basic.Publish x= rk=q1 
   1145 0.092889028    127.0.0.1             127.0.0.1             AMQP     88     Content-Header 
   1146 0.092914558    127.0.0.1             127.0.0.1             TCP      66     5672 → 38245 [ACK] Seq=6474 Ack=11819 Win=44800 Len=0 TSval=80646070 TSecr=80646070
   1147 0.093017735    127.0.0.1             127.0.0.1             AMQP     87     Basic.Ack 
   1148 0.093080236    127.0.0.1             127.0.0.1             AMQP     85     Basic.Publish x= rk=q1 
   1149 0.093139782    127.0.0.1             127.0.0.1             AMQP     88     Content-Header 
   1150 0.093164226    127.0.0.1             127.0.0.1             TCP      66     5672 → 38245 [ACK] Seq=6495 Ack=11860 Win=44800 Len=0 TSval=80646070 TSecr=80646070
   1151 0.093289324    127.0.0.1             127.0.0.1             AMQP     87     Basic.Ack 
   1152 0.133350995    127.0.0.1             127.0.0.1             TCP      66     38245 → 5672 [ACK] Seq=11860 Ack=6516 Win=44800 Len=0 TSval=80646080 TSecr=80646070```

I don't know yet where it is coming from, but that last "38245 → 5672 [ACK]" is breaking the pattern. In the details of that package it says:
`This is an ACK to the segment in frame: 1151`

**Comment by michaelklishin** [comment] 2017-03-21 20:49
Publisher confirms are sent out asynchronously and yes, there can be batching involved. It depends on how the downstream components (queues, message store, consumers) operate and there are multiple factors that affect this.

**Comment by michaelklishin** [comment] 2017-03-21 20:51
You are looking at different acks in this flow: TCP acks and AMQP 0-9-1 acks (publisher confirms and consumer acknowledgements).

`basic.ack` frames in AMQP 0-9-1 have a property called `multiple` which can be set to true or false. It should be reasonably easy to see in Wireshark but not command line tcpdump output. You can take a tcpdump produced file and shove it into Wireshark.

**Comment by michaelklishin** [comment] 2017-03-21 20:53
Since https://github.com/streadway/amqp/pull/246 we aren't aware of any known issues with publisher confirm handling in this client.

I'm pretty sure your code will hang after one ack frame acks multiple publishes.

**Comment by bojan-embroker** [comment] 2017-03-21 21:39
>You are looking at different acks in this flow: TCP acks and AMQP 0-9-1 acks (publisher confirms and consumer acknowledgements).

I mentioned that seemingly rouge TCP ACK at the end because i always see it when Channel.Publish blocks.

Can you help me understand how batched Basic.Ack would cause Channel.Publish to block? My code always publishes a single message and then waits for Basic.Ack. What would RabbitMQ acknowledge in a `mutliple` acknowledgement in my case? Can it acknowledge a message twice?

>I'm pretty sure your code will hang after one ack frame acks multiple publishes.

According to wireshark all Basic.Ack are not `multiple`.

**Comment by michaelklishin** [comment] 2017-03-21 22:05
Are you aware of [resource alarms](http://www.rabbitmq.com/alarms.html) and the fact that RabbitMQ can throttle publishers? See server logs, the alarms are quite visible.

**Comment by michaelklishin** [comment] 2017-03-21 22:07
Batched `basic.acks` cannot block `basic.publish` (well, there's [internal flow control](https://www.rabbitmq.com/blog/2015/10/06/new-credit-flow-settings-on-rabbitmq-3-5-5/) but it's transient under normal circumstances) but alarms will. I was referring to an expectation in your loop.

**Comment by bojan-embroker** [comment] 2017-03-21 23:36
I was not. I will check the logs.

Channel.Publish blocks indefinitely, but if I stop the process and run it again it will continue publishing (until next block). Is that expected behavior or RabbitMQ and the golang library? Also, I was able to reproduce with 1 second sleeps  - you can see where i did that in the commented line of the test case.

> Are you aware of resource alarms and the fact that RabbitMQ can throttle publishers

Wireshark shows that basic.publish isn't sent when Channel.Publish blocks.

>I was referring to an expectation in your loop.

Is that expectation incorrect in this loop if we assume that this process is the only publisher? Is there an example of how to implement reliable publishing in general case?

**Comment by michaelklishin** [comment] 2017-03-22 00:21
If you stop what process? If you restart RabbitMQ then all alarms are cleared but the free disk space will very quickly go into effect again.

If you restart this client and it gets stuck again it's expected. It's still not an indication that the issue is in this library, though.

Apparently we have [an example producer that uses publisher confirms](https://github.com/streadway/amqp/blob/master/_examples/simple-producer/producer.go).

**Comment by bojan-embroker** [comment] 2017-03-22 00:30
I meant to say when i restart client which was stuck indefinitely, it continues publishing without problems, until it gets stuck again randomly again.

**Comment by michaelklishin** [comment] 2017-03-22 08:55
If I were you I'd check that you are running the most recent version and then inspect the process e.g. to find out what line it is blocking on (likely a receive) and add debug logging.

So far there is no evidence that this is a client library problem => closing as a question/RCA thread.

**Closed by michaelklishin** 2017-03-22 08:55 UTC
Labels: question

**Comment by bojan-embroker** [comment] 2017-03-22 15:30
I am running the latest version. I was able to find where it blocks. It is this line:

https://github.com/streadway/amqp/blob/master/confirms.go#L32

**Comment by bojan-embroker** [comment] 2017-03-22 23:17
This is what RabbitMQ logs from when i run the test case to when it blocks:
```
=INFO REPORT==== 23-Mar-2017::00:14:58 ===
accepting AMQP connection <0.26278.2> (127.0.0.1:48725 -> 127.0.0.1:5672)
```

**Comment by bojan-embroker** [comment] 2017-03-23 00:35
Found the problem!

In my test case, this
`confirmationChan := channel.NotifyPublish(make(chan amqp.Confirmation))`
should be
`confirmationChan := channel.NotifyPublish(make(chan amqp.Confirmation, 1))`

Documentation says
```
The capacity of the chan Confirmation must be at least as large as the
number of outstanding publishings.  Not having enough buffered chans will
create a deadlock if you attempt to perform other operations on the Connection
or Channel while confirms are in-flight.
```
Seems like that the deadlock I have been hitting. I don't understand what other operations are being performed that are causing the deadlock, but making the channel buffered did fix my problem.

@michaelklishin, thanks for helping out. I found this while comparing my code to the producer example.

**Comment by michaelklishin** [comment] 2017-03-23 00:38
@bojan-embroker good to hear you figured it out. The first sentence makes a lot of sense, the rest I'd have to clarify with the author next time we have a maintainer meeting :)

**Comment by orange4glace** [comment] 2017-07-19 14:16
I encountered same problem and just figured out why blocking happens.
```go
func main() {
	conn, _ := amqp.Dial("amqp://guest:guest@localhost:5672")
	channel, _ := conn.Channel()
	q, _ := channel.QueueDeclare("q", false, false, false, false, nil)
	channel.Confirm(false)
	closeS := make(chan *amqp.Error)
	confirm := channel.NotifyPublish(make(chan amqp.Confirmation))
	for {
		channel.Publish(
			"",
			q.Name,
			false,
			false,
			amqp.Publishing{
				ContentType: "text/plain",
				Body:        []byte("hello"),
			})
		con := <-confirm
	}
}
```

when `channel.Publish()` is called, normally this things happen sequentially
1. network io will write to the socket (called by channel.Publish)
2. increase the internal confirmation counter (called by channel.Publish)
3. receives a confirmation
4. signal to the confirmation channel
5. con := <- confirm (in main function)

there are two goroutine in this steps.
one is for writing(1, 2, 5), the other is for reading(3, 4)
so 1, 2, 5 (write to network) and 3, 4 (read from network) are running on separate goroutine.

> 
> step 2, increasing internal confirmation counter
> step 4, signal to the confirmation channel

are sharing same mutex object.

Sometimes, the order can be different if the confirmation response comes really really fast.

1. network io will write to the socket (called by channel.Publish)
2. **receives a confirmation**
3. **signal to the confirmation channel.** 
4. **increase the internal confirmation counter** (called by channel.Publish)
5. con := <- confirm (in main function)

now 1, 4, 5 is on writing goroutine and 2, 3 is on reading goroutine.
for convenience, let's call writing goroutine as main goroutine and reading goroutine as sub goroutine.

Here's the detail.
At step 2, when receiving a confirmation from server, It locks the mutex.
At step 3, it will signal to confirmation channels which are registered by `ch.NotifyPublish()`. 
now, since the channel is an unbuffered channel, blocking occurs until another goroutine consumes a message from the channel.
At step 4, In main goroutine, it tries to lock the mutex but sub goroutine already locks it. the main goroutine waits for unlock.
To unlock the mutex from sub goroutine, step 5, consuming confirmation from the channel must happen.
But look, in main goroutine, function channel.Publish() is still ongoing since we are still at step 3.
We have to reach step 5 to consume a message from the confirmation channel but main goroutine can't go further since it can't dominate the mutex.

**Comment by michaelklishin** [comment] 2017-07-19 14:50
@orange4glace thank you, debugging such issues is always fairly time consuming. Would you be interested in submitting a PR that explores the idea(s)?

**Comment by orange4glace** [comment] 2017-07-19 17:39
It will be honored if I can contribute it but actually leaving it away might be fine since user can handle it like creating new go routine for the confirmation channel or just simply make a buffered channel.
In fact, I've thought if there's a way to improve it but it ends up with giving up because it should change the API (use something else instead of channel) in my modified implementation :P

**Comment by gaigepr** [comment] 2018-01-08 23:42
I am having the issue @bojan-embroker originally described even though I am using a buffered channel. I am trying to open just 1 channel and have a single thread use it to publish AND confirm publication. however, I get a deadlock after N+1 messages have been sent where N is the size of the buffered channel.

```
func openChannelToRabbitmq(con *amqp.Connection) *amqp.Channel {
	var ch *amqp.Channel
	var err error

	ch, err = con.Channel()
	if err != nil {
		log.Fatal("Failed to open AMQP channel... Exiting")
	}

	err = ch.Confirm(false)
	if err != nil {
		log.Printf("Channel could not be put into confirm mode: %s", err)
	}

	log.Println("Opened AMQP channel!")
	return ch
}

func confirmOne(confirms <-chan amqp.Confirmation) error {
	log.Printf("Waiting for confirmation of one publishing... ")
	confirmed := <-confirms
	if confirmed.Ack {
		log.Printf("Confirmed delivery with delivery tag: %d\n", confirmed.DeliveryTag)
		return nil
	}

	return fmt.Errorf("Failed to confirm delivery of one w/tag: %d", confirmed.DeliveryTag)
}

func publishAndConfirmRun(ch *amqp.Channel, job *jobDescription) error {
	confirms := ch.NotifyPublish(make(chan amqp.Confirmation, 1))
	defer confirmOne(confirms)

	err := ch.Publish(
		job.exchange,
		job.inputQueue,
		true,  // Mandatory
		false, // Immediate
		amqp.Publishing{
			ContentType:  "application/json",
			DeliveryMode: amqp.Persistent,
			ReplyTo:      job.outputQueue,
			Body:         []byte(job.payload),
		},
	)

	if err != nil {
		return fmt.Errorf("Failed to publish message to queue %s: %s", job.inputQueue, err)
	}

	return nil
}

```

**Comment by itscaro** [comment] 2019-10-17 01:42
@gaigepr Hello, did you find out why there is a deadlock after N+1 messages sent? I'm having the same issue :-<
