### ISSUE TITLE
TxCommit() blocks when connection fails

### ISSUE THREAD

**Issue by s-lau** [streadway/amqp#256] opened 2017-04-06 13:44 UTC
Hi,

I recently changed my AMQP code from confirm to transaction based processing.
It appears that if a connection fails now, the TxCommit function blocks forever
and I have no idea how to recover in that case.
Furthermore the connection error channel is still empty.

Any idea what might be the problem here and how to fix that?

Below you find a minimal working example and some output:
```golang
package main

import (
	"github.com/streadway/amqp"
	"time"
)

func main() {
	var (
		queueConn         *amqp.Connection
		connection_errors chan *amqp.Error
		channel           *amqp.Channel
		message_id        uint64
		err               error
		queue_chan               = make(chan *amqp.Publishing, 10240)
		queue_name        string = "queue"
		tx_size           uint64 = 1024
	)

	queueConn, err = amqp.Dial("amqp://127.0.0.1:5671")
	if err != nil {
		panic(err)
	}

	defer queueConn.Close()

	connection_errors = make(chan *amqp.Error)
	queueConn.NotifyClose(connection_errors)

	channel, err = queueConn.Channel()
	if err != nil {
		panic(err)
	}
	defer channel.Close()

	err = channel.ExchangeDeclare(queue_name, "direct", true, false, false, false, nil)
	if err != nil {
		panic(err)
	}
	_, err = channel.QueueDeclare(queue_name, true, false, false, false, nil)
	if err != nil {
		panic(err)
	}
	err = channel.QueueBind(queue_name, queue_name, queue_name, false, nil)
	if err != nil {
		panic(err)
	}

	err = channel.Tx()
	if err != nil {
		panic(err)
	}

	go func() {
		for {
			queue_chan <- &amqp.Publishing{
				Headers:         amqp.Table{},
				ContentType:     "text/plain",
				ContentEncoding: "UTF-8",
				Body:            []byte("foo"),
				DeliveryMode:    amqp.Persistent,
				Priority:        0,
			}
		}
	}()

	go func() {
		for {
			println("cerrors", len(connection_errors))
			time.Sleep(1 * time.Second)
		}
	}()

	message_id = 0
	for {
		select {
		case con_err := <-connection_errors:
			panic(con_err.Error())
			break
		case qmsg := <-queue_chan:
			err = channel.Publish(queue_name, queue_name, true, false, *qmsg)

			message_id++

			if err != nil {
				panic(err)
			}

			if message_id%tx_size == 0 {
				println("precommit")
				err = channel.TxCommit()
				println("comitted")
				if err != nil {
					panic(err)
				}
			}
		}
	}
}
```

Output:
```
cerrors 0
precommit
comitted
precommit
comitted
precommit
comitted
precommit
comitted
precommit
comitted
precommit
cerrors 0
cerrors 0
cerrors 0
cerrors 0
cerrors 0
cerrors 0
^Csignal: interrupt
```

Your AMQP source I used is at `afe8eee`, go is `1.7.5 linux/amd64`, rabbit is `3.5.7`.

Kind regards,
s-lau

**Comment by michaelklishin** [comment] 2018-03-07 22:34
This is a duplicate of #304: the lack of channel operation timeouts.

**Closed by michaelklishin** 2018-03-07 22:34 UTC
